CREATE TABLE AUTHORS (
	id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE POSTS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    SUMMARY VARCHAR(255) NOT NULL,
    BODY TEXT NOT NULL,
    DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    AUTHOR_ID INT NOT NULL
);

ALTER TABLE POSTS ADD CONSTRAINT fk_author_id FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID);

INSERT INTO authors(name, email) VALUES
('Riyaz Ahmed', 'riyaz24@gmail.com'),
('Razi Rameez', 'rameez10@gmail.com');

select * from authors;

ALTER TABLE posts 
RENAME COLUMN ID TO id; 

